name: Build image

on:
  workflow_run:
    workflows: ["Build .NET APP"]
    types:
      - completed

env:
  image: '${{ secrets.LOGIN }}/movie_library'

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Create Docker Image
        run: dotnet publish src/IO.Swagger/IO.Swagger.csproj /t:PublishContainer -r linux-x64
      
      - name: change image tag
        run: docker tag io-swagger ${{ env.image }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.LOGIN }}
          password: ${{ secrets.PASSWORD }}
      - name: Docker Push
        run: docker push ${{ env.image }}
