name: Push image

on:
  workflow_run:
    workflows: ["Build image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Push image
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.KEY }}
        port: 49203
        script: |
          docker pull katewlasova/movie_library:latest
          docker stop movie_library || true
          docker rm movie_library || true
          docker run -d -p 5000:80 --name movie_library katewlasova/movie_library:latest
